// <auto-generated />
using System;
using GemVogue.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GemVogue.Data.Migrations
{
    [DbContext(typeof(GemVogueDbContext))]
    partial class GemVogueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GemVogue.Data.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Магазина предлага изключителна селекция висококачествени бижута от подбрани колекции за да удовлетворим нуждите на тези, които вярват, че бижутата не са просто аксесоар. При нас всеки може да намери перфектното бижу,с което да зарадва себе си, да изненада любим човек или да впечатли с подарък, който ще привлече погледите на всички.Освен сертификат за автентичност можете да видите знака ALE щампован на нашите бижута, с изключение само на най-малките ни елементи. Еквивалентът във Великобритания е знакът на спонсора, а в Дания – знак на отговорност.Нашето стерлингово сребро е маркирано с главно S за сребро, последвано от чистотата на среброто, която е цитирана като единици чисто сребро на хиляда: S925 (92.5% чисто сребро).",
                            ImageUrl = "\\Images\\pandora-logo.png",
                            Name = "Pandora"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Официалните бижутата са подходящи за различни поводи, като сватби, юбилеи, балове, приеми и други. Можете да избирате между разнообразие от модели и стилове, които отговарят на вашите предпочитания и тоалет. Независимо дали предпочитате класически или модерни дизайни, бижутата Victoria Princess ще ви очароват със своята красота и изящество.Официалните бижута са не само прекрасен аксесоар, но и ценен подарък за любим човек. Ако искате да изненадате вашата половинка, майка, сестра или приятелка с нещо специално, можете да изберете бижу от нашата колекцията, което ще говори вместо вас за вашите чувства и уважение. Бижутата Victoria Princess са символ на любов, приятелство и лоялност.",
                            ImageUrl = "\\Images\\victoria princess-logo.png",
                            Name = "Victoria Princess"
                        },
                        new
                        {
                            Id = 3,
                            Description = "GOTO порасна, отвори магазин и в Испания, а с годините се превърна в наложена марка, символ на разнообразие, качество и класа, на която повече от 20 000 лоялни клиенти се довериха. Огромна привилегия и чест, носеща със себе си сериозна отговорност. Тя ни задължава да продължаваме да се усъвършенстваме, за да сбъднем нашата мисия и най-голяма мечта – името на GOTO да се свързва с любовта, обичта и топлия спомен, облечени в качество и стил на световно ниво.",
                            ImageUrl = "\\Images\\goto-logo.jpg",
                            Name = "Goto"
                        });
                });

            modelBuilder.Entity("GemVogue.Data.Models.Favorite", b =>
                {
                    b.Property<int>("JewelId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("JewelId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("GemVogue.Data.Models.Jewel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Jewelry");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 3,
                            CreatedOn = new DateTime(2024, 3, 10, 18, 56, 38, 380, DateTimeKind.Local).AddTicks(8716),
                            Description = "Сребърно колие с Феникс.Феникса е символ на унищожаване на старият и начало на новият по-добър живот.Размер на синджира: с регулиране от 42 до 45 смРазмер на феникса: 22x20 мм",
                            ImageUrl = "\\Images\\kolie-feniks.jpg",
                            Material = "Материал: Сребро, Камъни: кристали цирконийКарат: 925.0",
                            Name = "Колие Феникс",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CreatedOn = new DateTime(2024, 3, 10, 18, 56, 38, 380, DateTimeKind.Local).AddTicks(8766),
                            Description = "Сребърен пръстен с изключително рядка зелена разновидност на скъпоценният камък Аметист.Произход на камъка Бразилия.Вярва се, че бижутата от аметист помагат на притежателя си да очарова хората около себе си, като засилва харизматичното му излъчване.Размер на камъка: 8x6 мм, 2,3 cм",
                            ImageUrl = "\\Images\\prsten-ss-zelen-ametist.jpg",
                            Material = "Материал: СреброКамъни: скъпоценен камък зелен АметистКарат: 925.0",
                            Name = "Пръстен със зелен аметист",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            CreatedOn = new DateTime(2024, 3, 10, 18, 56, 38, 380, DateTimeKind.Local).AddTicks(8769),
                            Description = "Гривна Pandora Moments Звездопад.Този продукт е съвместим само с модели от колекция Pandora MomentsКарат: 925.0",
                            ImageUrl = "\\Images\\grivna-zvezdopdad.png",
                            Material = "Материал :СреброКамъни: Кубичен цирконий, КристалКарат: 925.0",
                            Name = "Гривна Звездопад",
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            CreatedOn = new DateTime(2024, 3, 10, 18, 56, 38, 380, DateTimeKind.Local).AddTicks(8774),
                            Description = "Обеци Game of Thrones x Pandora Домът на дракона",
                            ImageUrl = "\\Images\\domut-na-drakona.png",
                            Material = "Материал :СреброКамъни:КристалКарат: 925.0",
                            Name = " Домът на дракона",
                            Type = 4
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            CreatedOn = new DateTime(2024, 3, 10, 18, 56, 38, 380, DateTimeKind.Local).AddTicks(8776),
                            Description = "Дамски сребърен пръстен с 18К бяла позлата и създадени диаманти и сапфир.",
                            ImageUrl = "\\Images\\srebaren-prusten-sudadenid-sapfir.jpeg",
                            Material = "Материал:СреброКамъни: Създаден диамант, Създадени Скъпоценни Камъни.Карат: 925.0",
                            Name = "Сребърен пръстен с диаманти от сапфир",
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            CreatedOn = new DateTime(2024, 3, 10, 18, 56, 38, 380, DateTimeKind.Local).AddTicks(8779),
                            Description = " Сребърна дамска гривна за крак-класически стил.",
                            ImageUrl = "\\Images\\damska-grivna-za-krak.jpeg",
                            Material = "Материал: СреброКарат: 925.0",
                            Name = "Дамска гривна за крак",
                            Type = 3
                        });
                });

            modelBuilder.Entity("GemVogue.Data.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("GemVogue.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "41dde345-cc88-41c1-89c2-44ff9c7bd729",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "302d3a19-b866-474b-b8f7-e51ade3ffada",
                            Email = "admin@gemvogue.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Администратор",
                            NormalizedEmail = "ADMIN@GEMVOGUE.COM",
                            NormalizedUserName = "ADMIN@GEMVOGUE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEONjC2iuMmYnHW3ud0vQ9xjxeXoWlKEcduWzb3Ivx4Bh65riAM1MmXrDaX6Ci87v7A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1125a5fa-7672-4313-b267-fd4f619a2afa",
                            TwoFactorEnabled = false,
                            UserName = "admin@gemvogue.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e4b72d1-a0cf-43c7-837a-22543f3c1745",
                            ConcurrencyStamp = "8e4b72d1-a0cf-43c7-837a-22543f3c1745",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "41dde345-cc88-41c1-89c2-44ff9c7bd729",
                            RoleId = "8e4b72d1-a0cf-43c7-837a-22543f3c1745"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GemVogue.Data.Models.Favorite", b =>
                {
                    b.HasOne("GemVogue.Data.Models.Jewel", "Jewel")
                        .WithMany("Favorites")
                        .HasForeignKey("JewelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GemVogue.Data.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jewel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GemVogue.Data.Models.Jewel", b =>
                {
                    b.HasOne("GemVogue.Data.Models.Brand", "Brand")
                        .WithMany("Jewels")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GemVogue.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GemVogue.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GemVogue.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GemVogue.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GemVogue.Data.Models.Brand", b =>
                {
                    b.Navigation("Jewels");
                });

            modelBuilder.Entity("GemVogue.Data.Models.Jewel", b =>
                {
                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("GemVogue.Data.Models.User", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
